version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/mediafiles
    expose:
      - 8000
    env_file:
      - ./backend/backend/.env.production
    depends_on:
      - db
  db:
    image: postgres:14.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./db/.env
  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/mediafiles
      - type: volume
        source: ssl_volume
        target: /etc/ssl/ladispe
        read_only: true
    env_file:
      - ./frontend/nginx/.env.production
    secrets:
      - source: ssl_certificate  
        target: ladispe.crt
      - source: ssl_key
        target: ladispe.key
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend


volumes:
  postgres_data:
  static_volume:
  media_volume:
  ssl_volume: