# Generated by Django 4.0.3 on 2022-08-03 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ladicontent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ladistory',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ladistaff',
            name='user',
            field=models.ForeignKey(help_text='If you create a LADIStaff with a particular user, his name, surname and email will be public', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ladipicture',
            name='gallery',
            field=models.ForeignKey(blank=True, help_text='Select the gallery where you want to show the picture', null=True, on_delete=django.db.models.deletion.CASCADE, to='ladicontent.ladigallery'),
        ),
        migrations.AddField(
            model_name='ladipicture',
            name='news',
            field=models.ForeignKey(blank=True, help_text="You can link the picture to a news (link redirection won't work)", null=True, on_delete=django.db.models.deletion.SET_NULL, to='ladicontent.ladinews'),
        ),
        migrations.AddField(
            model_name='ladinews',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ladigallery',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
