# Generated by Django 4.0.3 on 2023-02-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladicontent', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ladigallery',
            name='title',
            field=models.CharField(help_text='REMARK:<br>If you want to display a gallery in the home, create a gallery named Home', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='ladinews',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
