# Generated by Django 4.0.3 on 2023-02-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladiusers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ladiuser',
            name='email',
            field=models.EmailField(help_text='\n        REMARKS:<br>\n        * in order to make <b>IS_BORSISTA</b> true for a user the group <b>Borsisti</b> should be created and he has to be added;<br>\n        * in order to make <b>IS_PROFESSOR</b> true for a user the group <b>Professors</b> should be created and he has to be added.\n        ', max_length=255, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='ladiuser',
            name='staff',
            field=models.BooleanField(default=False, help_text='Required for the admin page.'),
        ),
        migrations.AlterField(
            model_name='ladiuser',
            name='superuser',
            field=models.BooleanField(default=False, help_text='Only superusers can add or change superusers.'),
        ),
    ]
