# Generated by Django 4.0.3 on 2022-08-03 18:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import filebrowser.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LADICourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('public', models.BooleanField(default=True)),
                ('course_code', models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{2}[A-Z]{5}$', 'Course code in the format ##XXXXX')])),
                ('cover', filebrowser.fields.FileBrowseField(default='default.png', max_length=200, verbose_name='Image')),
                ('title', models.CharField(max_length=60, unique=True)),
                ('degree_course', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True, help_text='Use &lt;br&gt; to break the line')),
            ],
        ),
        migrations.CreateModel(
            name='LADILecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('cover', filebrowser.fields.FileBrowseField(default='default.png', max_length=200, verbose_name='Image')),
                ('html', tinymce.models.HTMLField(blank=True)),
                ('author', models.CharField(blank=True, max_length=30)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ladicourses.ladicourse')),
            ],
        ),
    ]
