# Generated by Django 4.0.3 on 2023-02-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladicourses', '0003_ladicourse_private_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='ladicourse',
            name='course_site',
            field=models.URLField(blank=True, help_text='URL of the official site of the course (required if mandatory redirection is enabled).'),
        ),
        migrations.AddField(
            model_name='ladicourse',
            name='mandatory_redirection',
            field=models.BooleanField(default=False, help_text='Set to True if you want to disable the LADICourse page and instead\n                                                redirect to the official site when Open is clicked (course site field is required).'),
        ),
    ]
