# Generated by Django 4.0.3 on 2023-02-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladicourses', '0004_ladicourse_course_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ladilecture',
            name='lecture_url',
            field=models.URLField(blank=True, help_text='URL to be opened insted of the standard LADISPE site page.'),
        ),
    ]
